### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'cookie_expiry_days'

### ISSUE THREAD

**Issue by bharath5673** [Sven-Bo/streamlit-sales-dashboard-with-userauthentication#1]
![Screenshot from 2022-09-12 12-12-35](https://user-images.githubusercontent.com/33729709/189589509-1d7b58dd-0100-4245-9677-ef6b52d92709.png)

**Comment by bharath5673** [comment]
> ![Screenshot from 2022-09-12 12-12-35](https://user-images.githubusercontent.com/33729709/189589509-1d7b58dd-0100-4245-9677-ef6b52d92709.png)


![Screenshot from 2022-09-12 12-15-59](https://user-images.githubusercontent.com/33729709/189589933-57a6a5af-f228-4120-8e7d-211f700c7c16.png)

`pip install streamlit-authenticator==0.1.5`

got worked after..!!

**Comment by biscotty666** [comment]
Thank you

**Comment by fadjeigah** [comment]
still not working for me
